<?php
$servername="localhost";
$mysql_user="root";
$mysql_pass="OIBiyRHYcN64";
$dbname="databaseproject";
$conn=mysqli_connect($servername,$mysql_user,$mysql_pass,$dbname);
if($conn){
    echo("connection");
}
?>